
spring: 
  datasource : 
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/bootex
    username : bootuser
    password : bootuser
    
  jpa : 
    hibernate:
      ddl-auto : update
    properties:
      hibernate :
        format_sql : true
    show-sql : true
    
  thymeleaf : 
    cache : false
---

  kakao:
  client_id:  32ebae90c437ccbb483cd0fb790fed86
  redirect_uri: http://localhost:8080/costomlogin/kakao